"""add_loans

Revision ID: 0703644c005a
Revises: 794ff7806994
Create Date: 2026-07-04 17:22:47.089877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0703644c005a'
down_revision: Union[str, Sequence[str], None] = '794ff7806994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'HOME', 'CAR', 'EDUCATION', 'CREDIT_CARD', name='loantype'), nullable=False),
    sa.Column('lender', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('total_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emi_day', sa.Integer(), nullable=False),
    sa.Column('remaining_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_tenure', sa.Integer(), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('first_emi_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='loanstatus'), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'PAID', 'LATE', name='paymentstatus'), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_loan_id', 'loans', ['loan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('fk_transactions_loan_id', type_='foreignkey')
        batch_op.drop_column('loan_id')
    op.drop_table('loan_payments')
    op.drop_table('loans')
    # ### end Alembic commands ###
